config/routes.rb
FootballPredictions::Application.routes.draw do

  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :predictions, :only => [:index, :new, :create]
  resources :fixtures, :only => [:index, :new, :create]
  resources :leagues, :only => [:new, :create]
  resources :mini_leagues, :only => [:index, :new, :create]
  resources :teams, :only => [:index, :new, :create]
  resources :enrollments, :only => [:index, :new, :create]


  scope :controller => :predictions do
    get 'index'

  end
 

  scope :controller => :main do
    get 'index'
    get 'fixturelist'
    get 'leaguetable'
  end

  scope :controller => :members do
    get 'index'
  end

  # Directing the user after login
  authenticated :user do
    root :to => 'members#index'
  end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'main#index'


  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
   attr_accessible :team_id, :mini_league_id

   belongs_to :team
   belongs_to :mini_league

   validate :valid_key?

    protected
    def valid_key?
      errors.add(:base, "Invalid key") unless team.key == mini_league.league_key
    end
end

app/models/fixture.rb
class Fixture < ActiveRecord::Base
  attr_accessible :home_team, :away_team, :fixture_date, :kickoff_time, :prediction_id

  #has_many :predictions
  

end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/league.rb
class League < ActiveRecord::Base
  attr_accessible :position, :team_name, :played, :goal_difference, :points
end

app/models/mini_league.rb
class MiniLeague < ActiveRecord::Base
  attr_accessible :league_name, :league_key
  
  has_many :teams, through: :enrollments
end

app/models/prediction.rb
class Prediction < ActiveRecord::Base
   attr_accessible :home_team, :away_team, :home_score, :away_score, :fixture_date, :fixture_id, :user_id

   has_one :fixture

   validate :fixture_id, :uniqueness => { :scope => :user_id, :message => "only one prediction per game is allowed, for each user" }

end

app/models/team.rb
class Team < ActiveRecord::Base
   attr_accessible :team_name, :user_id, :key

   belongs_to :user
   has_many :mini_leagues

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, 
  # :lockable, :timeoutable 
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook, :google_oauth2]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :prediction_id, :provider, :uid
  # attr_accessible :title, :body

  has_many :predictions
  has_many :teams

  def skip_confirmation!
   self.confirmed_at = Time.now
 end

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
  user = User.where(:provider => auth.provider, :uid => auth.uid).first
  unless user
    user = User.new(name:auth.extra.raw_info.name,
                         provider:auth.provider,
                         uid:auth.uid,
                         email:auth.info.email,
                         password:Devise.friendly_token[0,20]
                         )
    user.skip_confirmation!
    user.save
    
  end
  user
end


def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end


def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
    data = access_token.info
    user = User.where(:email => data["email"]).first

    unless user
        user = User.new(name: data["name"],
             email: data["email"],
             password: Devise.friendly_token[0,20]
            )
        user.skip_confirmation!
        user.save
    end
    user
end


end

app/controllers/fixtures_controller.rb
class FixturesController < ApplicationController

def index
    @fixtures = Fixture.all
  end

  def new
    @fixture = Fixture.new
  end

  def create 
    @fixture = Fixture.new(params[:fixture])
    if @fixture.save
      redirect_to root_path
    else
      render :new
    end
  end
  
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  def new
    @league = League.new
  end
 
  def create
   @league = League.new(params[:league])
    if @league.save
      redirect_to root_path
    else
      render :new
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  include LeagueGrabber::GetTable

	def index

	end

	def fixturelist
	  @fixtures = Fixture.all
	  @fixture_date = @fixtures.group_by {|fd| fd.fixture_date }

	end

  def leaguetable
    @league = League.all
  end
  
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_filter :authenticate_user!
  def index
  	three_days_from_today = Date.today + 3
    @fixtures = Fixture.where("fixture_date <= ?", three_days_from_today)
    @fixture_date = @fixtures.group_by {|fd| fd.fixture_date}

  end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  def index
    @team = Team.all

  end

  def new
    @team = current_user.teams.new

  end

  def create
    @team = current_user.teams.new(params[:team])
    if @team.save
      redirect_to root_path, :notice => 'Team Succcessfully Created'
    else
      render :new
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def login_status
    if user_signed_in?
      link_to("Logout", destroy_user_session_path, :confirm => "Are you sure you want to logout", :method => :delete)
    else
      link_to("Login", new_user_session_path)
    end
  end

  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  #enables omniauth in shared links
  def resource_class
    devise_mapping.to
  end

end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/fixtures_helper.rb
module FixturesHelper
  def date_format(date)
    date.to_date.strftime("#{date.to_date.day.ordinalize} %b %Y")
  end

end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/mini_leagues_helper.rb
module MiniLeaguesHelper
end

app/helpers/predictions_helper.rb
module PredictionsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/main/fixturelist.html.erb
<%= link_to "Make Predictions", new_prediction_path %>
<h1>Fixture List</h1>

<% @fixture_date.sort.each do |date, fixtures| %>
  <h4><%= date_format(date) %></h4>

  <% fixtures.each do |fixture| %>
    <%= fixture.home_team %> VS <%= fixture.away_team %><br>
  <% end %>
<% end %>

app/views/main/index.html.erb
<div class="container">
	<div class="row">
  	<div class="span6 offset3 well">
       <%= form_for(resource, :as => resource_name, :html => {class:"form-horizontal"}, :url => session_path(resource_name))  do |f| %>
       <fieldset>
        <div id="legend">
         <legend class="">Login</legend>
        </div>
       <div class="control-group">
        	<%= f.label :email, :class => "control-label" %>
        	 <div class="controls">
             <%= f.email_field :email, :autofocus => true %>
           </div>
        </div>

        <div class="control-group">
  	    	<%= f.label :password, :class => "control-label" %>
  	    		<div class="controls">
    					<%= f.password_field :password %>
    				</div>
    		</div>

  <% if devise_mapping.rememberable? -%>
    <div class="control-group">
    	<%= f.label :remember_me, :class => "control-label" %>
    	<div class="controls">
    		<%= f.check_box :remember_me %> 
    </div>
    </div>
  <% end -%>

  <div class="form-actions">
  	<%= f.submit "Sign in", :class => 'btn btn-primary' %>
  </div>
</fieldset>
<% end %>



  	</div>
	</div>
</div>

app/views/main/leaguetable.html.erb
<div class="league-table-content">
  <table class="table-stats">
    <thead>
      <tr class="header">
        <th class="position">Pos</th>
        <th class="team-name">Team</th>
        <th class="played">P</th>
        <th class="goal-difference">GD</th>
        <th class="points">Pts</th>
      </tr>
    </thead>
    <tbody>
      <% @league.each do |l| %>
     <tr class="team">
      <td class="position"><%= l.position %></td>
      <td class="team-name"><%= l.team_name %></td>
      <td class="played"><%= l.played %></td> 
      <td class="goal-difference"><%= l.goal_difference %></td> 
      <td class="points"><%= l.points %></td> 
      <% end %>



     </tr>


    </tbody>

</table>
</div>

app/views/members/index.html.erb
    <div class="container">
    	<div class="row">
        <div class="span4">
         <div class="well">
          <h2 class="muted">Make Predictions</h2>
           <%= form_tag controller: 'predictions', action: 'create', method: 'post' do %>
           <%= error_messages_for :prediction %>
           <% @fixture_date.sort.each do |date, fixture| %>
           <ul class="fixture-dates">
           <li><h5><%= date_format(date) %></h5></li>
           </ul>

           <ul class="fixtures">
           <% fixture.each do |fixture|%>
    
           <li>
           	<span class="home-team"><%= fixture.home_team %></span> 
           	<span class="score">
           	<%= text_field_tag "predictions[][home_score]" %> 
            <%= text_field_tag "predictions[][away_score]" %>
            </span>
           	<span class="away-team"><%= fixture.away_team %></span> 
          
           </li>
           <%= hidden_field_tag "predictions[][home_team]", fixture.home_team %>
           <%= hidden_field_tag "predictions[][away_team]", fixture.away_team %>

           <%= hidden_field_tag "predictions[][fixture_date]", fixture.fixture_date %>
           <%= hidden_field_tag "predictions[][fixture_id]", fixture.id %>
           <%= hidden_field_tag "predictions[][user_id]", current_user.id %>
         
           <% end %>
           </ul>
          <% end %>
          <%= submit_tag "Submit predictions", :class => "btn btn-success btn-large" %>
          <% end %>
        </div>
       </div>


    <div class="span4">
    <div class="well">
    <h2 class="text-warning">Previous Results</h2>
    <p><span class="label label-success">POPULAR</span></p>
    <ul>
    <li>20 users</li>
    <li>Unlimited access with no limits</li>
    <li>5TB of space</li>
    </ul>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta.</p>
    <hr>
    <h3>$10.99 / month</h3>
    <hr>
    <p><a class="btn btn-success btn-large" href="#"><i class="icon-ok"></i> Select plan</a></p>
    </div>
    </div>
    <div class="span4">
    <div class="well">
    <h2 class="text-info">Your Score</h2>
    <p><span class="label label-info">BUDGET</span></p>
    <ul>
    <li>10 users</li>
    <li>5TB of space</li>
    </ul>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta.</p>
    <hr>
    <h3>$8.99 / month</h3>
    <hr>
    <p><a class="btn btn-large" href="#"><i class="icon-ok"></i> Select plan</a></p>
    </div>
    </div>


   </div>
  </div>





<h1>Members Area</h1>
<%= "Hi #{current_user.name}" %><br>
<%= login_status %><br>
<%= link_to "Make Predictions", new_prediction_path %><br>
<%= link_to "View Current Predictions", predictions_path %><br>
<%= link_to "See all Fixtures", fixturelist_path %><br>
<%= link_to "See League Table", leaguetable_path %><br>
<%= link_to "Create Mini League", new_mini_league_path %><br>
<%= link_to "See all Leagues", mini_leagues_path %><br>
<%= link_to "Create Team", new_team_path %><br>
<%= link_to "See all Teams", teams_path %><br>
<%= link_to "Join Mini League", new_enrollment_path %>
<%= link_to "My Mini League's", enrollments_path %>