config/routes.rb
FootballPredictions::Application.routes.draw do

  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :predictions, :only => [:index, :new, :create]
  resources :fixtures, :only => [:index, :new, :create]
  resources :leagues, :only => [:new, :create]
  resources :mini_leagues, :only => [:index, :new, :create]
  resources :teams, :only => [:index, :new, :create]
  resources :enrollments, :only => [:index, :new, :create]


  scope :controller => :predictions do
    get 'index'

  end
 

  scope :controller => :main do
    get 'index'
    get 'fixturelist'
    get 'leaguetable'
  end

  scope :controller => :members do
    get 'index'
  end

  # Directing the user after login
  authenticated :user do
    root :to => 'members#index'
  end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'main#index'


  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
   attr_accessible :team_id, :mini_league_id

   belongs_to :team
   belongs_to :mini_league

   validate :valid_key?

    protected
    def valid_key?
      errors.add(:base, "Invalid key") unless team.key == mini_league.league_key
    end
end

app/models/fixture.rb
class Fixture < ActiveRecord::Base
  attr_accessible :home_team, :away_team, :fixture_date, :kickoff_time, :prediction_id

  #has_many :predictions
  

end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/league.rb
class League < ActiveRecord::Base
  attr_accessible :position, :team_name, :played, :goal_difference, :points
end

app/models/mini_league.rb
class MiniLeague < ActiveRecord::Base
  attr_accessible :league_name, :league_key
  
  has_many :teams, through: :enrollments
end

app/models/prediction.rb
class Prediction < ActiveRecord::Base
   attr_accessible :home_team, :away_team, :home_score, :away_score, :fixture_date, :fixture_id, :user_id

   has_one :fixture

   validate :fixture_id, :uniqueness => { :scope => :user_id, :message => "only one prediction per game is allowed, for each user" }

end

app/models/team.rb
class Team < ActiveRecord::Base
   attr_accessible :team_name, :user_id, :key

   belongs_to :user
   has_many :mini_leagues

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, 
  # :lockable, :timeoutable 
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook, :google_oauth2]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :prediction_id, :provider, :uid
  # attr_accessible :title, :body

  has_many :predictions
  has_many :teams

  def skip_confirmation!
   self.confirmed_at = Time.now
 end

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
  user = User.where(:provider => auth.provider, :uid => auth.uid).first
  unless user
    user = User.new(name:auth.extra.raw_info.name,
                         provider:auth.provider,
                         uid:auth.uid,
                         email:auth.info.email,
                         password:Devise.friendly_token[0,20]
                         )
    user.skip_confirmation!
    user.save
    
  end
  user
end


def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end


def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
    data = access_token.info
    user = User.where(:email => data["email"]).first

    unless user
        user = User.new(name: data["name"],
             email: data["email"],
             password: Devise.friendly_token[0,20]
            )
        user.skip_confirmation!
        user.save
    end
    user
end


end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  def new
    @league = League.new
  end
 
  def create
   @league = League.new(params[:league])
    if @league.save
      redirect_to root_path
    else
      render :new
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  include LeagueGrabber::GetTable

	def index

	end

	def fixturelist
	  @fixtures = Fixture.all
	  @fixture_date = @fixtures.group_by {|fd| fd.fixture_date }

	end

  def leaguetable
    @league = League.all
  end
  
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  def index
    @team = Team.all

  end

  def new
    @team = current_user.teams.new

  end

  def create
    @team = current_user.teams.new(params[:team])
    if @team.save
      redirect_to root_path, :notice => 'Team Succcessfully Created'
    else
      render :new
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def login_status
    if user_signed_in?
      link_to("Logout", destroy_user_session_path, :confirm => "Are you sure you want to logout", :method => :delete)
    else
      link_to("Login", new_user_session_path)
    end
  end

  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  #enables omniauth in shared links
  def resource_class
    devise_mapping.to
  end

end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/fixtures_helper.rb
module FixturesHelper
  def date_format(date)
    date.to_date.strftime("#{date.to_date.day.ordinalize} %b %Y")
  end

end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/mini_leagues_helper.rb
module MiniLeaguesHelper
end

app/helpers/predictions_helper.rb
module PredictionsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/confirmable/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <title>FootballPredictions</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% if user_signed_in? %>
	 <%= render 'shared/usernavbar' %>
	 <% else %>
	 <%= render 'shared/navbar' %>
	<% end %>
		<% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">×</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    </div>
  <% end %>


<%= yield %>

</body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-fixed-top">
   <div class="navbar-inner">
     <div class="container">
       <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
       </a>
       <a class="brand" href="../">Premier Predictions</a>
       <div class="nav-collapse collapse" id="main-menu">
        <ul class="nav pull-right">
          <li><%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %></li>
          <li><%= link_to "Sign in with Google", user_omniauth_authorize_path(:google_oauth2) %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
       </div>
     </div>
   </div>
 </div>

app/views/shared/_usernavbar.html.erb
<div class="navbar navbar-fixed-top">
   <div class="navbar-inner">
     <div class="container">
       <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
       </a>
       <a class="brand" href="../">Premier Predictions</a>
       <div class="nav-collapse collapse" id="main-menu">
        <ul class="nav pull-right">
          <li><%= link_to "#{current_user.name}", edit_user_registration_path %></li>
          <li><%= login_status %></li>
          
       </div>
     </div>
   </div>
 </div>